### ISSUE TITLE
Incorrect license definition

### ISSUE THREAD

**Issue by fooishbar** [OpenMandrivaAssociation/libopenaptx#2]
Hi,
In the update to note the new license, several mentions of the old license still remain (grep the spec file for '2.1'). However it is important to note that the license is _not_ LGPLv3, as it contains additional restrictions. Please see [this PipeWire issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/664) for more details.

**Comment by AngryPenguinPL** [comment]
We talked about it a while ago and decided to downgrade the package to version 0.2.0 - before the license change, so that we could use it without licensing problems in pipewire.
